### PR TITLE
Add refuel module, increase bleed to 10

### LINKED ISSUE #71: Without ACE Refuel Module, refueling with fuel trucks takes very long
If we add the ACE Refuel Module to the framework by default, and leave it on it's default setting, refueling via fuel trucks and the new fuel line won't take more than 15 minutes

### PR DESCRIPTION
**Pull request by AACO**
resolves #71 and #78

### CODE REVIEW

**Comment by zerithsmash** [comment]
Is 10x too much? I'm asking because I have no idea how low the bleed rate is currently. Obviously it's pretty slow right now w/ forever unconciousness.

**Comment by PabstMirror** [comment]
10x bleed is a big jump, we might want to start at 5x and go from there?

**Comment by AACO** [comment]
I'll reduce it to 5x, I just wanted a jumping off point. Right now bleed out takes about 10 minutes, so besides pain and perhaps getting gimped, non lethal wounds aren't really a concern.

**Comment by zerithsmash** [comment]
We toyed with this back in the AGM days and yeah it's probably better to slowly creep it up. I think we went too far in AGM and people were bleeding out/going unconscious before they could apply a bandage.

**Pull request merged**
