### PR TITLE
Updated common.hpp with Splints & Ger. Loadout fixes

### PR DESCRIPTION
**Pull request by ArgoChris**
Updated common.hpp by replacing Morphine with splints in BASE_MEDICAL, also increased morphine count and added splints to MEDIC_MEDICAL

### CODE REVIEW

**Comment by ArgoChris** [comment]
Added fixes to the german loadouts as well

**Comment by BadWolf64** [comment]
Just tracking this, did you remove the changes that you were making in regards to moving the loadouts to separate folders?

**Comment by ArgusDoesGitHub** [comment]
Yeah that really sucks

**Comment by PabstMirror** [comment]
I'm pretty sure this has been replaced by alabm's work big rework and can be closed?

**Comment by ArgoChris** [comment]
Covered in latest loadout and Potato unit overhaul

**Pull request closed without merging**
