### PR TITLE
Adds FAC to 3 default factions

### PR DESCRIPTION
**Pull request by Alex6511**
FAC is equiped with abnormal smoke colors and a laser designator with batteries by default.

### CODE REVIEW

**Comment by AACO** [comment]
The FACs should probably have a pretty separate load out compared to PLT+ officers. No GP/Thrown frags, perhaps reduced ammo, thrown Chems/IR Strobes/Smokes (can probably reduce/remove the covering white smokes). No pistol/mags. They should be a pretty pure support role instead of a kill role. Their main tools should be the Radio, the laser designation, and the map.

How is this implemented for the other templates (MSV/USMC/Airborne)

**Comment by Alex6511** [comment]
I don't agree with removing their normal smokes/frags, at the end of the day every member of the platoon is still a rifleman.

I'll make some adjustments to the other stuff, their ammo could be brought down a bit.

Haven't decided how I'm going to do this in MSV, Marines/Airborne have a dedicated FAC

**Comment by AACO** [comment]
If a medic can live without frags so can the FAC. And while they won't have white cover smoke, they'll have more smoke than a fireteam.

**Comment by Alex6511** [comment]
Pistol/mags/frags removed
chemlights added for night ops

**Comment by Alex6511** [comment]
Also I said this on discord but I think the MSV template (which is supposed to be for ground ops anyway, the helos are just added for parallelism with the other templates) has enough radios in its command structure to just make someone a FAC on the spot.

**Pull request closed without merging**
