### PR TITLE
BWMF Rework

### PR DESCRIPTION
**Pull request by Alablm**
Reworks the BWMF to make use of potato units, thus allowing further expansion on the default factions. This rework also includes a medical update, see https://github.com/BourbonWarfare/bwmf/commit/7e1d479ed9af7bb84fd4ea1c2d7cbe24d475d405 for details.

Major changes:
Dedicated Zeus slots
FACs
HMG
HAT
Artillery
Engineer team modification (Leader, 2x demo, 2x mine)
Addition of unique leader slots to all weapons teams and 2ICs
Addition of UAV to MSV
MSV Rework, making it compatible with default loadouts

### CODE REVIEW

**Comment by Alablm** [comment]
This is not ready to me merged: All loadouts currently need to be updated to include units added in the rework.

**Comment by Alablm** [comment]
Alright, at this point it's just going to be tweaking the loadouts on the new units, and as such I'm going to be looking for some people to help play barbie. Once the loadouts are complete I believe this will be okay to implement, pending review.

**Comment by Alablm** [comment]
There's about 20 loadouts left to update and test. This should be 100% wrapped code-wise by mid next week, I'm not going to have much time for it until then. After that I'd like to try and organize a mass test before we start using it in session.

**Comment by Alablm** [comment]
With the previous commit this is done, pending a testing session. I have tested all the loadouts myself to ensure they are functional, but would like another set of eyes to have a look.

**Comment by PabstMirror** [comment]
This looks good and I think we can make the switch over
Only little bookkeeping things left would be to 
- update description.ext with a new date 
- readme.md with a new version

**Review by BadWolf64 — APPROVED** [review]
Looks good.

**Comment by Alablm** [comment]
This is ready to ship from my side.

**Review by PabstMirror — APPROVED** [review]

**Pull request merged**
